// <auto-generated />
using System;
using Api.Infraestrutura.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251119002316_mensalista")]
    partial class mensalista
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Modelos.Entidades.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DtAgendamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtagendamento");

                    b.Property<int>("IdBarbeiro")
                        .HasColumnType("integer")
                        .HasColumnName("idbarbeiro");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metodopagamento");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomecliente");

                    b.Property<string>("NumeroCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numerocliente");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdBarbeiro");

                    b.ToTable("agendamento", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.AgendamentoHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAgendamento")
                        .HasColumnType("integer")
                        .HasColumnName("idagendamento");

                    b.Property<int>("IdBarbeiroHorario")
                        .HasColumnType("integer")
                        .HasColumnName("idbarbeirohorario");

                    b.HasKey("Id");

                    b.HasIndex("IdAgendamento");

                    b.HasIndex("IdBarbeiroHorario");

                    b.ToTable("agendamentohorario", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.AgendamentoServico", b =>
                {
                    b.Property<int>("IdAgendamento")
                        .HasColumnType("integer")
                        .HasColumnName("idagendamento");

                    b.Property<int>("IdServico")
                        .HasColumnType("integer")
                        .HasColumnName("idservico");

                    b.HasKey("IdAgendamento", "IdServico");

                    b.HasIndex("IdServico");

                    b.ToTable("agendamentoservico", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.Barbeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acesso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acesso");

                    b.Property<string>("Agenda")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipoagenda");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTimeOffset>("DtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtcadastro");

                    b.Property<DateTime?>("DtDemissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtdemissao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea")
                        .HasColumnName("foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("barbeiro", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.BarbeiroHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtfim");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtinicio");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<int>("IdBarbeiro")
                        .HasColumnType("integer")
                        .HasColumnName("idbarbeiro");

                    b.Property<string>("TipoDia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipodia");

                    b.HasKey("Id");

                    b.HasIndex("IdBarbeiro");

                    b.ToTable("barbeirohorario", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.BarbeiroHorarioExcecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BarbeiroHorarioId")
                        .HasColumnType("integer")
                        .HasColumnName("idbarbeirohorario");

                    b.Property<DateTime>("DtExcecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtexcecao");

                    b.Property<int>("MotivoExcecao")
                        .HasColumnType("integer")
                        .HasColumnName("motivoexcecao");

                    b.HasKey("Id");

                    b.HasIndex("BarbeiroHorarioId")
                        .IsUnique();

                    b.ToTable("barbeirohorarioexcecao", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.BarbeiroServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtfim");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtinicio");

                    b.Property<int>("IdBarbeiro")
                        .HasColumnType("integer")
                        .HasColumnName("idbarbeiro");

                    b.Property<int>("IdServico")
                        .HasColumnType("integer")
                        .HasColumnName("idservico");

                    b.HasKey("Id");

                    b.HasIndex("IdBarbeiro");

                    b.HasIndex("IdServico");

                    b.ToTable("barbeiroservico", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.CategoriaServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtfim");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtinicio");

                    b.HasKey("Id");

                    b.ToTable("categoriaservico", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.CodigoConfirmacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmado");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtcriacao");

                    b.Property<DateTime>("DtExpiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtexpiracao");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<bool>("Reenviado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("tokenconfirmacao", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.Mensalista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtfim");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtinicio");

                    b.Property<int>("IdBarbeiro")
                        .HasColumnType("integer")
                        .HasColumnName("idbarbeiro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdBarbeiro");

                    b.ToTable("mensalista", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.MensalistaDia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DiaSemana");

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("time")
                        .HasColumnName("Horario");

                    b.Property<int>("MensalistaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MensalistaId")
                        .IsUnique();

                    b.ToTable("mensalistadia", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtfim");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtinicio");

                    b.Property<int>("IdCategoriaServico")
                        .HasColumnType("integer")
                        .HasColumnName("idcategoriaservico");

                    b.Property<TimeOnly>("TempoEstimado")
                        .HasColumnType("time")
                        .HasColumnName("tempoestimado");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaServico");

                    b.ToTable("servico", (string)null);
                });

            modelBuilder.Entity("Api.Modelos.Entidades.Agendamento", b =>
                {
                    b.HasOne("Api.Modelos.Entidades.Barbeiro", "Barbeiro")
                        .WithMany("Agendamentos")
                        .HasForeignKey("IdBarbeiro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agendamento_barbeiro");

                    b.Navigation("Barbeiro");
                });

            modelBuilder.Entity("Api.Modelos.Entidades.AgendamentoHorario", b =>
                {
                    b.HasOne("Api.Modelos.Entidades.Agendamento", "Agendamento")
                        .WithMany("AgendamentoHorarios")
                        .HasForeignKey("IdAgendamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modelos.Entidades.BarbeiroHorario", "BarbeiroHorario")
                        .WithMany()
                        .HasForeignKey("IdBarbeiroHorario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("BarbeiroHorario");
                });

            modelBuilder.Entity("Api.Modelos.Entidades.AgendamentoServico", b =>
                {
                    b.HasOne("Api.Modelos.Entidades.Agendamento", "Agendamento")
                        .WithMany("AgendamentoServicos")
                        .HasForeignKey("IdAgendamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modelos.Entidades.Servico", "Servico")
                        .WithMany("AgendamentoServicos")
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Api.Modelos.Entidades.BarbeiroHorario", b =>
                {
                    b.HasOne("Api.Modelos.Entidades.Barbeiro", null)
                        .WithMany("BarbeiroHorarios")
                        .HasForeignKey("IdBarbeiro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modelos.Entidades.BarbeiroHorarioExcecao", b =>
                {
                    b.HasOne("Api.Modelos.Entidades.BarbeiroHorario", "BarbeiroHorario")
                        .WithOne("BarbeiroHorarioExcecao")
                        .HasForeignKey("Api.Modelos.Entidades.BarbeiroHorarioExcecao", "BarbeiroHorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BarbeiroHorario");
                });

            modelBuilder.Entity("Api.Modelos.Entidades.BarbeiroServico", b =>
                {
                    b.HasOne("Api.Modelos.Entidades.Barbeiro", "Barbeiro")
                        .WithMany("BarbeiroServicos")
                        .HasForeignKey("IdBarbeiro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modelos.Entidades.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbeiro");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Api.Modelos.Entidades.Mensalista", b =>
                {
                    b.HasOne("Api.Modelos.Entidades.Barbeiro", null)
                        .WithMany("Mensalistas")
                        .HasForeignKey("IdBarbeiro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modelos.Entidades.MensalistaDia", b =>
                {
                    b.HasOne("Api.Modelos.Entidades.Mensalista", null)
                        .WithOne("Dia")
                        .HasForeignKey("Api.Modelos.Entidades.MensalistaDia", "MensalistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modelos.Entidades.Servico", b =>
                {
                    b.HasOne("Api.Modelos.Entidades.CategoriaServico", "CategoriaServico")
                        .WithMany("Servicos")
                        .HasForeignKey("IdCategoriaServico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaServico");
                });

            modelBuilder.Entity("Api.Modelos.Entidades.Agendamento", b =>
                {
                    b.Navigation("AgendamentoHorarios");

                    b.Navigation("AgendamentoServicos");
                });

            modelBuilder.Entity("Api.Modelos.Entidades.Barbeiro", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("BarbeiroHorarios");

                    b.Navigation("BarbeiroServicos");

                    b.Navigation("Mensalistas");
                });

            modelBuilder.Entity("Api.Modelos.Entidades.BarbeiroHorario", b =>
                {
                    b.Navigation("BarbeiroHorarioExcecao");
                });

            modelBuilder.Entity("Api.Modelos.Entidades.CategoriaServico", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("Api.Modelos.Entidades.Mensalista", b =>
                {
                    b.Navigation("Dia")
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modelos.Entidades.Servico", b =>
                {
                    b.Navigation("AgendamentoServicos");
                });
#pragma warning restore 612, 618
        }
    }
}
